language: node_js
language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '4.1'
before_script:
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: npm@niteoholdings.com
  api_key:
    secure: N3VdJy5D2gxAfY3o8V4JtN1tyC8XqCvJofNmGDMwFl9gVp/CIzaiaKFdZBwNKHmvS4t3g6EsVbJPlkTsec4PbX75Y8F/c2Hdk8inu/SEQoYydePUdsE+KJkLKAVue57mLV+4MzLSz6loAGjMpwuBluaCZ4G7K1T67v5PEt5TTpo=
  on:
    all_branches: true
    tags: true
    repo: VeriShip/grunt-niteo-aws
    node: '4.1'
