language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - npm install
script:
  - grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: "BbjhhB504nlHST3rXLEw8ixsf/MycPddbEBu8O3c1eRIMrxyJVSP4PhTG9WFZmPwLhjgcFNh5inNfczcYwAukYIR7YxTzwR4Wcb29R83ffInsmuwVdxK3bSRc0dcy6+UP16Gwg1nv3CuPjRLur/6bSDXoVvl7/U//m4bj+qRG1k="
  on:
    tags: true
    all_branches: true
    repo: NiteoSoftware/grunt-niteo-aws

